server:
  port: 9000

spring:
  application.name: gateway-service
  cloud:
    gateway:
      routes:
        - id: currency-exchange-service
          uri: lb://CURRENCY-EXCHANGE-SERVICE
          predicates:
            - Path=/currency-exchange/**
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'